# -*- coding:utf-8 -*-
"""
Django settings for StudyOnline project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$6e6h!47^o9uan=4*cf+89$yh=yybat06c=0y6$o$e0-l+gf+q'

# SECURITY WARNING: don't run with debug turned on in production!
# 生产环境中必须关闭
DEBUG = False

# *表示所有
ALLOWED_HOSTS = ['*', ]

# 自定义的验证方法（在apps/users/views）
AUTHENTICATION_BACKENDS = (
    'users.views.CustomBackend',
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',      # 对request做拦截，根据session id查找session data（用户信息）
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'courses',
    'organization',
    'operation',
    'xadmin',
    'crispy_forms',
    'captcha',
    'pure_pagination',
    'DjangoUeditor',
]

AUTH_USER_MODEL = 'users.UserProfile'

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'StudyOnline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [     # 上下文处理器
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.media',     # 把MEDIA_URL注册到模板文件
            ],
        },
    },
]

WSGI_APPLICATION = 'StudyOnline.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'studyonline',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '192.168.1.1',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

EMAIL_HOST = 'smtp.sina.com'            # 邮箱服务器ip
EMAIL_PORT = 25                         # 邮箱服务器端口
EMAIL_HOST_USER = ''                    # 邮箱地址
EMAIL_HOST_PASSWORD = ''                # 邮箱密码
EMAIL_USE_TLS = False
EMAIL_FROM = 'yipwinghong@sina.com'         

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 10,     # 中间显示个数
    'MARGIN_PAGES_DISPLAYED': 2,    # 两边显示个数（其余用...表示）
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}

STATIC_URL = '/static/'
# 生产环境（debug关闭）下不起作用，可以参考MEDIA的方法自己配置个访问函数
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# 生产环境下开启（开发环境下要关闭，否则影响上述配置）
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
