# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_userfavorite_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '\u8bfe\u7a0b'), (2, '\u8bfe\u7a0b\u673a\u6784'), (3, '\u8bb2\u5e08')], verbose_name='\u6536\u85cf\u7c7b\u578b'),
        ),
    ]
