# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseResourse',
            new_name='CourseResource',
        ),
    ]
