# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 15:59
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_bannercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', null=True, verbose_name='\u8bfe\u7a0b\u8be6\u60c5'),
        ),
    ]
