# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
    ]
